languageCode = "en-us"
title = "DEV Akimbo"
enableRobotsTXT = true

summaryLength = 20 # 320 characters Google Rich snippet length

[social]
  facebook = "devakimbo"
  twitter = ""
  facebook_admin = ""

[imaging]
  quality = 90

[taxonomies]
  # category = "categories"
  # series = "series"
  tag = "tags"
  author = "authors"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "autumn"
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
    # section = ["HTML", "RSS", "JSON"]
                 # taxonomyTerm = ["HTML", "RSS", "JSON"]
    # taxonomy = ["HTML", "RSS", "JSON"]
