baseURL = "https://devakimbo.com/"
# baseURL = "http://localhost:5000"
languageCode = "en-us"
title = "Dev Akimbo"
enableRobotsTXT = true

[social]
facebook = "devakimbo"
twitter = ""

[imaging]
quality = 90

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "autumn"
    tabWidth = 4
