baseURL = "https://devakimbo.com/"
# baseURL = "http://localhost:5000"
languageCode = "en-us"
title = "Dev Akimbo"
enableRobotsTXT = true

[social]
facebook = "devakimbo"
twitter = ""

[imaging]
quality = 100