[[matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=2592000, no-transform, public"
gzip = true

[[matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=2592000, no-transform, public"
gzip = false

[[matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
