[[mounts]]
source = "static"
target = "static"

[[mounts]]
source = "static/fonts"
target = "static/fonts"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "assets/plugins"
target = "assets/plugins"

[[mounts]]
source = "static/plugins"
target = "static/plugins"

[[mounts]]
source = "node_modules/@fortawesome/fontawesome-free/webfonts"
target = "static/webfonts"

[[mounts]]
source = "node_modules/fuse.js/dist"
target = "static/plugins/fuse"

# [[mounts]]
# source = "node_modules/jquery/dist"
# target = "static/plugins/jquery"

# [[mounts]]
# source = "node_modules/bootstrap/dist/js"
# target = "static/plugins/bootstrap"

# [[mounts]]
# source = "node_modules/animate.css"
# target = "assets/plugins/animate.css"

# [[mounts]]
# source = "node_modules/slick-carousel/slick"
# target = "assets/plugins/slick-carousel"

# [[mounts]]
# source = "node_modules/slick-carousel/slick"
# target = "static/plugins/slick-carousel"

# [[mounts]]
# source = "node_modules/aos/dist"
# target = "static/plugins/aos"

# [[mounts]]
# source = "node_modules/slick-carousel/slick/ajax-loader.gif"
# target = "static/css/ajax-loader.gif"

# [[mounts]]
# source = "node_modules/slick-carousel/slick/fonts"
# target = "static/css/fonts"

# [[mounts]]
# source = "node_modules/@popperjs/core/dist/umd"
# target = "static/plugins/popper"

# [[mounts]]
# source = "node_modules/wow.js/dist"
# target = "static/plugins/wow"

# [[mounts]]
# source = "node_modules/mixitup/dist"
# target = "static/plugins/jquery.mixitup"

# [[mounts]]
# source = "node_modules/magnific-popup/dist/"
# target = "static/plugins/jquery-magnific-popup"

# [[mounts]]
# source = "node_modules/lazysizes"
# target = "static/plugins/lazysizes"

# [[mounts]]
# source = "node_modules/vanilla-lazyload/dist/lazyload.min.js"
# target = "static/plugins/lazyload.min.js"
