home = "Home"
logo = "/images/logo-oneliner.jpg"
# phone = "‭+44 7561399765‬"
email = "contact@devakimbo.com"
author = "Dev Akimbo"
owner = "Dev Akimbo"
title = "DEV Akimbo"
description = "We help ambitious individuals become the top paid IT professionals while building amazing lives worth living."
startYear = "2019-01-01"

# gtag = "GTM-WVDXKLS"
google_analytics_id = "UA-150778271-8"
facebook_id = "2662574160653636"
manychatId = ""
# copyright = "© 2016-2020 Appdy LTD"

showPublishedData = false
numRelatedPosts = 3
numListPosts = 9

[[authors]]
name = "Adam Faryna"
www = "devakimbo.com"
photo = "https://www.gravatar.com/avatar/239175829b11add1eeccf71c8916020f?s=120"
bio = "Adam is a seasoned software developer, fluent in more than 50 programming languages, tools, and frameworks. He started his IT career in 2007. He worked as an employee, contractor, freelancer, independent developer, mentor, teacher, and digital agency owner. These days he is focused on his passion for teaching and building online businesses."


[[popular]]
page = "/posts/python-3-installation-tutorial-for-beginners"

[[popular]]
page = "/posts/the-6-biggest-reasons-why-you-will-fail-to-learn-programming"

[[popular]]
page = "/posts/what-programming-language-to-learn-for-web-development-in-2021"

[[popular]]
page = "/posts/what-programming-language-to-learn-first-in-2021"

[[popular]]
page = "/posts/the-5-best-methods-to-learn-programming"


[[footer.links]]
label = "Privacy Policy"
URL = "privacy-policy"

[[footer.links]]
label = "Cookie Policy"
URL = "cookie-policy"

# [[footer.links]]
# label = "Terms Of Service"
# URL = "terms-of-service"

# [[footer.links]]
# label = "Business Contact"
# URL = "proposals"

# [[footer.links]]
# label = "Earnings Disclaimer"
# URL = "earnings-disclaimer"


# preloader
[preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

[navCta]
enable = false

[scrollToTop]
enable = false

# [[contact]]
# enabled = true

# [[cookies]]
# enable

# social site

[social.facebook]
enable = true
icon = "fab fa-facebook"
URL = "https://www.facebook.com/devakimbo"

[social.instagram]
enable = false
icon = "fab fa-instagram"
URL = "#"

[social.twitter]
enable = true
icon = "fab fa-twitter"
URL = "https://twitter.com/AdamFaryna"

[social.youtube]
enable = true
icon = "fab fa-youtube"
URL = "https://www.youtube.com/channel/UCP9kyhK4ET0lWapEGtlkwAw"

[social.pinterest]
enable = false
icon = "fab fa-pinterest-p"
URL = "#"

[social.github]
enable = true
icon = "fab fa-github"
URL = "https://github.com/adamfaryna"

[social.rss]
enable = true
icon = "fas fa-rss"


[modal]
enable = false


# preconnect
[[preconnect]]
link = "https://ssl.gstatic.com"

[[preconnect]]
link = "https://www.gstatic.com"

[[preconnect]]
link = "https://fonts.googleapis.com"


[[preload]]
link = "/webfonts/fa-brands-400.woff2"
as = "font"

[[preload]]
link = "/webfonts/fa-solid-900.woff2"
as = "font"

[[preload]]
link = "/fonts/Cabin/static/Cabin-SemiBold.ttf"
as = "font"

[[preload]]
link = "/fonts/Cabin/static/Cabin-Regular.ttf"
as = "font"

[[preload]]
link = "/fonts/Cabin/static/Cabin-Bold.ttf"
as = "font"

# JS assets
[[assets.js]]
link = "js/script.js"
async = true

# [[assets.js]]
# link = "js/lazy-image.js"
# async = true


# css plugins
# [[plugins.css]]
# link = "plugins/bootstrap/bootstrap.min.css"

# [[plugins.css]]
# link = "plugins/slick-carousel/slick.css"
# [[plugins.css]]
# link = "plugins/slick-carousel/slick-theme.css"
# [[plugins.css]]
# link = "plugins/animate.css/animate.min.css"

# [[plugins.css]]
# link = "plugins/jquery-magnific-popup/magnific-popup.css"
# [[plugins.css]]
# link = "plugins/webfonts/all.min.css" # font-awesome
# [[plugins.css]]
# link = "plugins/themify-icons/themify-icons.css"
# [[plugins.css]]
# link = "plugins/fontawesome/brands.min.css"
# [[plugins.css]]
# link = "plugins/fontawesome/fontawesome.min.css"
# [[plugins.css]]
# link = "plugins/fontawesome/solid.min.css"


# JS plugin
[[assets.js]]
link = "js/search.js"
async = true

# [[assets.js]]
# link = "js/subscription.js"
# async = true

[[static.js]]
link = "plugins/fuse/fuse.min.js"
async = true

# [[static.js]]
# link = "plugins/lazysizes/lazysizes.min.js"
# async = true

# [[static.js]]
# link = "plugins/lazysizes/plugins/unveilhooks/ls.unveilhooks.min.js"
# async = true

# [[static.js]]
# link = "plugins/jquery/jquery.min.js"

# [[static.js]]
# link = "plugins/popper/popper.min.js"
# async = true

# [[static.js]]
# link = "plugins/bootstrap/bootstrap.min.js"
# async = true

# [[static.js]]
# link = "plugins/slick-carousel/slick.min.js"

# [[static.js]]
# link = "plugins/wow/wow.min.js"

# [[static.js]]
# link = "plugins/jquery.mixitup/mixitup.min.js"

# [[static.js]]
# link = "plugins/jquery-magnific-popup/jquery.magnific-popup.js"

# [[static.js]]
# link = "plugins/aos/aos.js"

# [[assets.js]]
# link = "plugins/slick-carousel/slick.min.js"
