# baseURL = "https://appdy.github.io/"
baseURL = "http://localhost:5000"
languageCode = "en-us"
title = "Appdy"

[module]
[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "static/fonts"
target = "static/fonts"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "assets/plugins"
target = "assets/plugins"

[[module.mounts]]
source = "static/plugins"
target = "static/plugins"

[[module.mounts]]
source = "node_modules/@fortawesome/fontawesome-free/webfonts"
target = "static/webfonts"

[[module.mounts]]
source = "node_modules/@fortawesome/fontawesome-free/webfonts"
target = "static/plugins/fontawesome"

[[module.mounts]]
source = "node_modules/jquery/dist"
target = "static/plugins/jquery"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "static/plugins/bootstrap"

# [[module.mounts]]
# source = "node_modules/animate.css"
# target = "assets/plugins/animate.css"

[[module.mounts]]
source = "node_modules/slick-carousel/slick"
target = "assets/plugins/slick-carousel"

[[module.mounts]]
source = "node_modules/slick-carousel/slick"
target = "static/plugins/slick-carousel"

# [[module.mounts]]
# source = "node_modules/aos/dist"
# target = "static/plugins/aos"

[[module.mounts]]
source = "node_modules/slick-carousel/slick/ajax-loader.gif"
target = "static/css/ajax-loader.gif"

[[module.mounts]]
source = "node_modules/slick-carousel/slick/fonts"
target = "static/css/fonts"

[[module.mounts]]
source = "node_modules/@popperjs/core/dist/umd"
target = "static/plugins/popper"

[[module.mounts]]
source = "node_modules/wow.js/dist"
target = "static/plugins/wow"

[[module.mounts]]
source = "node_modules/mixitup/dist"
target = "static/plugins/jquery.mixitup"

[[module.mounts]]
source = "node_modules/magnific-popup/dist/"
target = "static/plugins/jquery-magnific-popup"

# css plugins
# [[params.plugins.css]]
# link = "plugins/bootstrap/bootstrap.min.css"

# [[params.plugins.css]]
# link = "plugins/slick-carousel/slick.css"
# [[params.plugins.css]]
# link = "plugins/slick-carousel/slick-theme.css"
# [[params.plugins.css]]
# link = "plugins/animate.css/animate.min.css"

# [[params.plugins.css]]
# link = "plugins/jquery-magnific-popup/magnific-popup.css"
# [[params.plugins.css]]
# link = "plugins/webfonts/all.min.css" # font-awesome
# [[params.plugins.css]]
# link = "plugins/themify-icons/themify-icons.css"
# [[params.plugins.css]]
# link = "plugins/fontawesome/brands.min.css"
# [[params.plugins.css]]
# link = "plugins/fontawesome/fontawesome.min.css"
# [[params.plugins.css]]
# link = "plugins/fontawesome/solid.min.css"

# js plugin
[[params.static.js]]
link = "plugins/jquery/jquery.min.js"
[[params.static.js]]
link = "plugins/popper/popper.min.js"
[[params.static.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.static.js]]
link = "plugins/slick-carousel/slick.min.js"
[[params.static.js]]
link = "plugins/wow/wow.min.js"
[[params.static.js]]
link = "plugins/jquery.mixitup/mixitup.min.js"
[[params.static.js]]
link = "plugins/jquery-magnific-popup/jquery.magnific-popup.js"
# [[params.static.js]]
# link = "plugins/aos/aos.js"

# [[params.assets.js]]
# link = "plugins/slick-carousel/slick.min.js"

[[menu.homepage]]
URL = "#service"
name = "Service"
weight = 1

[[menu.homepage]]
URL = "#portfolio"
name = "Portfolio"
weight = 2

[[menu.homepage]]
URL = "#about"
name = "About"
weight = 3

[[menu.homepage]]
URL = "#contact"
name = "Contact"
weight = 4


[[menu.main]]
URL = "/service/"
name = "Service"
weight = 1

[[menu.main]]
URL = "/portfolio/"
name = "Portfolio"
weight = 2

[[menu.main]]
URL = "/about/"
name = "About"
weight = 3

[[menu.main]]
URL = "/contact/"
name = "Contact"
weight = 4


[params]
home = "Home"
logoDark = "images/logo.png"
logoLight = "images/logo-white.png"
phone = ""
email = ""
skype = ""
author = "Appdy"
owner = "Appdy"
description = "Digital Agency Based in London"
startYear = "2016-01-01"

gtag = "GTM-WVDXKLS"
# google_analytics_id = "UA-129161973-1"
# copyright = "© Copyright 2016-2020 Appdy LTD"

[params.footer]
description = "Appdy LTD is a business registered in England and Wales since 2016.<br>Company number 10541738"

[params.footer.phone]
enable = false
title = "Call Us On"
phone = ""

[params.footer.email]
enable = false
title = "Mail us on"
email = ""

[params.footer.skype]
enable = false
title = "Lets Skype"
skype = ""

[[params.footer.links]]
label = "Privacy Policy"
URL = "privacy-policy"

[[params.footer.links]]
label = "Cookie Policy"
URL = "cookie-policy"

[[params.footer.links]]
label = "Terms Of Service"
URL = "terms-of-service"

[[params.footer.links]]
label = "Business Contact"
URL = "proposals"

# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

[params.navCta]
enable = false

[params.scrollToTop]
enable = true

# [[params.contact]]
# enabled = true

# [[params.cookies]]
# enable

# social site
[params.social.facebook]
enable = true
icon = "fab fa-facebook-f"
URL = "https://www.facebook.com/appdy.net"

[params.social.instagram]
enable = false
icon = "fab fa-instagram"
URL = "#"

[params.social.twitter]
enable = false
icon = "fab fa-twitter"
URL = "#"

[params.social.youtube]
enable = false
icon = "fab fa-youtube"
URL = "#"

[params.social.pinterest]
enable = false
icon = "fab fa-pinterest-p"
URL = "#"

[params.modal]
enable = false

# [blackfriday]
# extensions = ["hardLineBreak"]

# [markup.goldmark.renderer]
# hardWraps = true