baseURL = "http://example.org/"
languageCode = "en-us"
title = "Appdy"

[module]
[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "static/fonts"
target = "static/fonts"

[[module.mounts]]
source = "node_modules/@fortawesome/fontawesome-free/webfonts"
target = "static/webfonts"

[[module.mounts]]
source = "node_modules/jquery/dist"
target = "static/plugins/jquery"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "static/plugins/bootstrap"

[[module.mounts]]
source = "node_modules/animate.css"
target = "static/plugins/animate.css"

[[module.mounts]]
source = "node_modules/slick-carousel/slick"
target = "static/plugins/slick-carousel"

[[module.mounts]]
source = "node_modules/@popperjs/core/dist/umd"
target = "static/plugins/popper"

[[module.mounts]]
source = "node_modules/wow.js/dist"
target = "static/plugins/wow"

[[module.mounts]]
source = "node_modules/mixitup/dist"
target = "static/plugins/jquery.mixitup"

[[module.mounts]]
source = "node_modules/magnific-popup/dist/"
target = "static/plugins/jquery-magnific-popup"

# css plugins
# [[params.plugins.css]]
# link = "plugins/bootstrap/bootstrap.min.css"
# [[params.plugins.css]]
# link = "plugins/slick/slick.css"
# [[params.plugins.css]]
# link = "plugins/jquery-magnific-popup/jquery.magnific-popup.css"
# [[params.plugins.css]]
# link = "plugins/animate.css/animate.min.css"
# [[params.plugins.css]]
# link = "plugins/webfonts/all.min.css" # font-awesome
# [[params.plugins.css]]
# link = "plugins/themify-icons/themify-icons.css"

# js plugin
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/popper/popper.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick-carousel/slick.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/jquery.mixitup/mixitup.min.js"
[[params.plugins.js]]
link = "plugins/jquery-magnific-popup/jquery.magnific-popup.js"

[[menu.main]]
URL = "#service"
name = "Service"
weight = 1

[[menu.main]]
URL = "#clients"
name = "Clients"
weight = 2

[[menu.main]]
URL = "#free-case-study"
name = "Case Study"
weight = 3

[[menu.main]]
URL = "#about"
name = "About"
weight = 4

[[menu.main]]
URL = "#contact"
name = "Contact"
weight = 5


[params]
home = "Home"
logoDark = "images/template-one/logo.png"
logoLight = "images/template-one/logo-white.png"
phone = ""
email = ""
skype = ""
author = "Appdy LTD"
description = "Digital Agency Based in London"
startYear = "2016-01-01"

google_analytics_id = "" # Your ID
# copyright = "© Copyright 2016-2020 Appdy LTD"


[params.footer]
description = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam"

[[params.footer.links]]
label = "Privacy Policy"
URL = "privacy-policy"

[[params.footer.links]]
label = "Terms Of Service"
URL = "terms-of-service"

# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

[params.navCta]
enable = false

[params.scrollToTop]
enable = true

# [[params.contact]]
# enabled = true

# [[params.cookies]]
# enable

# social site
[params.social.facebook]
enable = true
icon = "fab fa-facebook-f"
URL = "#"

[params.social.instagram]
enable = false
icon = "fab fa-instagram"
URL = "#"

[params.social.twitter]
enable = false
icon = "fab fa-twitter"
URL = "#"

[params.social.youtube]
enable = false
icon = "fab fa-youtube"
URL = "#"

[params.social.pinterest]
enable = false
icon = "fab fa-pinterest-p"
URL = "#"
